baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Walter (Tianhao) Wu'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I'm a PhD student at the Unveristy of Cambridge, supervised by [Cengiz Ã–ztireli](https://www.cl.cam.ac.uk/~aco41/). My current research is mainly on image-based rendering and implicit neural representation. I'm interested in a wide range of topics including novel view synthesis, 3D reconstruction, video learning and scene decomposition.


# Selected Publications

### Gaussian Head & Shoulders: High Fidelity Neural Upper Body Avatars with Anchor Gaussian Guided Texture Warping


**Tianhao Wu**, Jing Yang, Zhilin Guo, Jingyi Wan, Fangcheng Zhong, Cengiz Oztireli

Arxiv

[ğŸ“„ Paper](https://arxiv.org/abs/2405.12069) | [ğŸŒ Project Page](https://gaussian-head-shoulders.netlify.app/)



### Neural Fields with Hard Constraints of Arbitrary Differential Order


Fangcheng Zhong, Kyle Fogarty, Param Hanji, **Tianhao Wu**, Alejandro Sztrajman, Andrew Spielberg, Andrea Tagliasacchi, Petra Bosilj, Cengiz Oztireli

NeurIPS 2023

[ğŸ“„ Paper](https://arxiv.org/abs/2306.08943) | [ğŸŒ Project Page](https://zfc946.github.io/CNF.github.io/)



### Î±Surf: Implicit Surface Reconstruction for Semi-Transparent and Thin Objects with Decoupled Geometry and Opacity


**Tianhao Wu**, Hanxue Liang, Fangcheng Zhong, Gernot Riegler, Shimon Vainer, Cengiz Oztireli

Arxiv

[ğŸ“„ Paper](https://arxiv.org/abs/2303.10083) | [ğŸŒ Project Page](https://alphasurf.netlify.app/)



### 


**Tianhao Wu**, Jing Yang, Zhilin Guo, Jingyi Wan, Fangcheng Zhong, Cengiz Oztireli

Arxiv

[ğŸ“„ Paper]() | [ğŸŒ Project Page]()



### D^2NeRF: Self-Supervised Decoupling of Dynamic and Static Objects from a Monocular Video


**Tianhao Wu**, Fangcheng Zhong, Andrea Tagliasacchi, Forrester Cole, Cengiz Oztireli

Arxiv

[ğŸ“„ Paper](https://arxiv.org/abs/2205.15838) | [ğŸŒ Project Page](https://d2nerf.github.io/)



### Kubric: a scalable dataset generator


Klaus Greff and Francois Belletti and Lucas Beyer and Carl Doersch and
Yilun Du and Daniel Duckworth and David J Fleet and Dan Gnanapragasam and
Florian Golemo and Charles Herrmann and Thomas Kipf and Abhijit Kundu and
Dmitry Lagun and Issam Laradji and Hsueh-Ti (Derek) Liu and Henning Meyer and
Yishu Miao and Derek Nowrouzezahrai and Cengiz Oztireli and Etienne Pot and
Noha Radwan and Daniel Rebain and Sara Sabour and Mehdi S. M. Sajjadi and Matan Sela and
Vincent Sitzmann and Austin Stone and Deqing Sun and Suhani Vora and Ziyu Wang and
**Tianhao Wu** and Kwang Moo Yi and Fangcheng Zhong and Andrea Tagliasacchi
Arxiv

[ğŸ“„ Paper](https://arxiv.org/abs/2203.03570) | [ğŸŒ Project Page](https://github.com/google-research/kubric)



"""

# Collection to display on home
# homeCollectionTitle = 'Posts'
# homeCollection = 'posts'


# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/waltertianhaowu/"

#[[params.social]]
#name = "medium"
#url = "https://medium.com/@user"

#[[params.social]]
#name = "github"
#url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

#[[params.menu]]
#name = "posts"
#url = "/posts"

[[params.menu]]
name = "CV"
url = "/cv"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"